### ISSUE TITLE
code

### ISSUE THREAD

**Issue by flynnamy** [CXH-Research/FilmNet#1]
Hi,it is a really interesting work! Any plans to share the code to train and test? @xuhangc

**Comment by xuhangc** [comment]
Thank you for your attention. We will release our code after the conference. Before that we have released our dataset.

**Comment by flynnamy** [comment]
Hi,any updates? @xuhangc

**Comment by zinuoli** [comment]
> Hi,any updates? @xuhangc 

Hi, IJCAI2023 will be held from August 19 to August 25 and our codes are expected to be released after the conference. 
We deeply appreciate your attention and kindly ask for your patience.

**Comment by xuhangc** [comment]
Hello, I have already pushed the code. If you encounter any issues, feel free to raise another issue. Thank you. @flynnamy
