### ISSUE TITLE
Pretrained Weights

### ISSUE THREAD

**Issue by sunyi123** [CXH-Research/FilmNet#3]
Are there any pre-trained checkpoints available?

**Comment by xuhangc** [comment]
Sorry we will not release checkpoints about FilmSet. But I think I can retrain FilmNet and provide checkpoints on MIT-Adobe FiveK and HDR+ soon.

**Comment by xuhangc** [comment]
> Are there any pre-trained checkpoints available?

@sunyi123 Hi! We've released the checkpoints for MIT-Adobe 5K and HDR+ for your convenience. You can find them here: https://github.com/CXH-Research/FilmNet/releases/tag/weights.
